name: Sync Bitwarden images to ACR(Alibaba Cloud Container Registry)

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  pull-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to the ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Pull bitwarden image from ghcr
        run: docker pull ghcr.io/bitwarden/self-host:beta

      - name: Tag bitwarden image for ACR
        run: docker tag ghcr.io/bitwarden/self-host:beta ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/bitwarden:beta

      - name: Push bitwarden image to Aliyun Registry
        run: docker push ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/bitwarden:beta
